openssl 1.1.1n
AnacondaRecipes/openssl-feedstock pull request #8
Opened 2022-03-17 10:30 UTC by skupr-anaconda

Actions:
1. Remove linux-generic32 from build.sh
2. Fix source/url with https
3. Add gh17902.patch: Avoid spurious errors when checking for 3.x engine

2022-03-17 10:57 UTC, skupr-anaconda commented
I wonder how conda-forge try to build v1.1.1n (https://github.com/conda-forge/openssl-feedstock/pull/83/files):
- To break circular dependency openssl -> clang -> ld64 -> sigtool -> openssl:
    `- {{ compiler('clang_bootstrap') }}  # [osx]`
- move `perl *` from `host` to `build` requirements

Should we use the same changes?

2022-03-17 12:58 UTC, chenghlee commented
> * To break circular dependency openssl -> clang -> ld64 -> sigtool -> openssl:
>   `- {{ compiler('clang_bootstrap') }}  # [osx]`

I don't think we need to do this unless using just `{{ compiler('c') }}` causes build failures on our macOS workers.

> * move `perl *` from `host` to `build` requirements

I recommend we pick up this change, as long as the Windows issue described in the current comment does not re-occur.

2022-03-17 12:59 UTC, chenghlee requested changes

2022-03-17 12:59 UTC, chenghlee commented on recipe/meta.yaml
> +    - patches/gh17902.patch
This backport seems to be from the OpenSSL 3.x branch, so I don't think we need to adopt it for our OpenSSL 1.1.1* build.

2022-03-17 13:09 UTC, skupr-anaconda commented on recipe/meta.yaml
> +    - patches/gh17902.patch
I removed it

2022-03-17 13:29 UTC, skupr-anaconda commented
> > * move `perl *` from `host` to `build` requirements
> 
> I recommend we pick up this change, as long as the Windows issue described in the current comment does not re-occur.

I moved `perl` froom `host` to `build`

2022-03-17 16:02 UTC, varlackc reviewed
The package looks good, however the `home_url` need to use `https`

2022-03-17 16:44 UTC, chenghlee approved these changes

2022-03-18 08:08 UTC, skupr-anaconda commented
> The package looks good, however the `home_url` need to use `https`

@varlackc Thank you. I fixed it

2022-03-18 13:15 UTC, varlackc approved these changes

2022-03-18 15:48 UTC, chenghlee approved these changes

2022-03-21 08:32 UTC, tobijk approved these changes
LGTM

2022-03-21 09:34 UTC, merged

2022-03-28 10:07 UTC, h-vetinari commented
> I moved `perl` from `host` to `build` but it failed on win32 and win64

The key to that was to change `%LIBRARY_BIN%\perl` in bld.bat to just `perl`, see https://github.com/conda-forge/openssl-feedstock/commit/7ba0303aa55ace703d0665edd457454d6a1b8b28

Also, is there a publicly available feedstock for openssl 3.0.0? I'd like to sync this back with conda-forge, because I saw that Anaconda managed to get cryptography to run with openssl 3.0.0, and I've been struggling to get that off the ground.